[features]
seeds = false
skip-lint = false
[programs.localnet]
calculator = "Hip3HFipM6fwKbfQtkUKCUUvk7uueMKMsfDyavpx7XpX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/d/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
